### ISSUE TITLE
Finish README

### ISSUE THREAD

**Issue by Hucxley** [KDM-TTS/KDM-TTS-Mod#12]
Complete the README for introducing the project, guiding people how to contribute to it, installing the mod, putting up resources to learn more about the physical game, and to serve as a proper landing zone for people interested in how the project is built.

**Comment by KHam0425** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Proper ReadMe](https://trello.com/c/ZrIiNBZg/12-proper-readme)

**Comment by KHam0425** [comment]
Spell checkers would be appreciated to scan over and see if anything needs fixed.
